/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as BooksCategoriesImport } from './routes/books/categories'
import { Route as BooksBookIdImport } from './routes/books/$bookId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BooksCategoriesRoute = BooksCategoriesImport.update({
  id: '/books/categories',
  path: '/books/categories',
  getParentRoute: () => rootRoute,
} as any)

const BooksBookIdRoute = BooksBookIdImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdImport
      parentRoute: typeof rootRoute
    }
    '/books/categories': {
      id: '/books/categories'
      path: '/books/categories'
      fullPath: '/books/categories'
      preLoaderRoute: typeof BooksCategoriesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/categories': typeof BooksCategoriesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/categories': typeof BooksCategoriesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/categories': typeof BooksCategoriesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/books/$bookId' | '/books/categories'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/books/$bookId' | '/books/categories'
  id: '__root__' | '/' | '/books/$bookId' | '/books/categories'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  BooksCategoriesRoute: typeof BooksCategoriesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  BooksCategoriesRoute: BooksCategoriesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/books/$bookId",
        "/books/categories"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/books/$bookId": {
      "filePath": "books/$bookId.tsx"
    },
    "/books/categories": {
      "filePath": "books/categories.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
